# Generated by Django 3.0.7 on 2020-06-09 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('type_of_event', models.CharField(max_length=255)),
                ('event_date', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mount_tsion_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('how_often', models.CharField(max_length=200)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='mount_tsion_app.User')),
            ],
        ),
    ]
