# Generated by Django 3.0.7 on 2020-06-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mount_tsion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
