# Generated by Django 3.0.7 on 2020-06-09 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mount_tsion_app', '0003_auto_20200609_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='mount_tsion_app.Register'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='mount_tsion_app.Event'),
            preserve_default=False,
        ),
    ]
